export const seedBooksLibrary = {
  schemaVersion: 1,
  books: {
    "book-1": {
      id: "book-1",
      title: "Meditations",
      subtitle: "",
      authorIds: ["author-marcus-aurelius"],
      author: "Marcus Aurelius",
      publisher: "",
      publicationYear: "",
      format: "paperback",
      source: "owned",
      status: "reading",
      purchasedDate: "",
      startedDate: "",
      completedDate: "",
      firstCompletedDate: "",
      lastCompletedDate: "",
      rereadCount: 0,
      rating: "10",
      pageCount: "",
      genre: "Philosophy",
      tags: ["stoicism", "philosophy"],
      isbn: "",
      coverUrl: "",
      favorite: true,
      notesCount: 0,
      quotesCount: 1,
      createdAt: "2026-05-27T00:00:00.000Z",
      updatedAt: "2026-05-27T00:00:00.000Z",
    },
    "book-2": {
      id: "book-2",
      title: "The Republic",
      subtitle: "",
      authorIds: ["author-plato"],
      author: "Plato",
      publisher: "",
      publicationYear: "",
      format: "hardcover",
      source: "owned",
      status: "completed",
      purchasedDate: "",
      startedDate: "",
      completedDate: "2026-01-15",
      firstCompletedDate: "2026-01-15",
      lastCompletedDate: "2026-01-15",
      rereadCount: 0,
      rating: "9",
      pageCount: "",
      genre: "Philosophy",
      tags: ["philosophy", "politics"],
      isbn: "",
      coverUrl: "",
      favorite: false,
      notesCount: 0,
      quotesCount: 0,
      createdAt: "2026-05-27T00:00:00.000Z",
      updatedAt: "2026-05-27T00:00:00.000Z",
    },
    "book-3": {
      id: "book-3",
      title: "The Myth of Sisyphus",
      subtitle: "",
      authorIds: ["author-albert-camus"],
      author: "Albert Camus",
      publisher: "",
      publicationYear: "",
      format: "ebook",
      source: "owned",
      status: "completed",
      purchasedDate: "",
      startedDate: "",
      completedDate: "2026-02-10",
      firstCompletedDate: "2026-02-10",
      lastCompletedDate: "2026-02-10",
      rereadCount: 0,
      rating: "10",
      pageCount: "",
      genre: "Philosophy",
      tags: ["existentialism", "philosophy", "absurdism"],
      isbn: "",
      coverUrl: "",
      favorite: true,
      notesCount: 0,
      quotesCount: 1,
      createdAt: "2026-05-27T00:00:00.000Z",
      updatedAt: "2026-05-27T00:00:00.000Z",
    },
  },
  authors: {
    "author-marcus-aurelius": {
      id: "author-marcus-aurelius",
      name: "Marcus Aurelius",
      tags: ["stoicism", "philosophy"],
    },
    "author-plato": {
      id: "author-plato",
      name: "Plato",
      tags: ["philosophy", "politics"],
    },
    "author-albert-camus": {
      id: "author-albert-camus",
      name: "Albert Camus",
      tags: ["existentialism", "absurdism"],
    },
  },
  quotes: {
    "quote-1": {
      id: "quote-1",
      bookId: "book-1",
      quote:
        "The happiness of your life depends upon the quality of your thoughts.",
      author: "Marcus Aurelius",
      tags: ["stoicism", "attention"],
      capturedAt: "2026-05-27T00:00:00.000Z",
    },
    "quote-2": {
      id: "quote-2",
      bookId: "book-3",
      quote: "One must imagine Sisyphus happy.",
      author: "Albert Camus",
      tags: ["absurdism", "meaning"],
      capturedAt: "2026-05-26T00:00:00.000Z",
    },
  },
  notes: {},
  readingSessions: {},
  imports: [],
};